# Generated by Django 4.0.6 on 2022-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=64)),
                ('email_to', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
