# Generated by Django 4.0.6 on 2022-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=30)),
                ('email_to', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=5)),
                ('base_ccy', models.CharField(max_length=5)),
                ('buy', models.DecimalField(max_digits=5, decimal_places=2)),
                ('sell', models.DecimalField(max_digits=5, decimal_places=2)),
            ],
        ),
    ]
