# Generated by Django 4.0.6 on 2022-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapps', '0002_source_alter_rate_buy_alter_rate_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='base_ccy',
            field=models.CharField(
                choices=[
                    ('UAH', 'Hhivna'),
                    ('USD', 'United States Dollar'),
                    ('EUR', 'Euro'),
                    ('BIT', 'Bitcoin')],
                default='UAH',
                max_length=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ccy',
            field=models.CharField(
                choices=[
                    ('UAH', 'Hhivna'),
                    ('USD', 'United States Dollar'),
                    ('EUR', 'Euro'),
                    ('BIT', 'Bitcoin')],
                max_length=5),
        ),
    ]
