# Generated by Django 4.1 on 2022-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapps', '0007_alter_responselog_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='query_params',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
